#!/bin/bash

# This bash script enters the running pasta based pyTools container

if podman container exists example_pytools_pod ; then

  reset
  echo ""
  echo Entering pyTools container in the podmanExample pod
  echo ""
  echo "------------------------------------------------------------------------"
  echo ""

  podman exec -it example_pytools_pod /bin/bash
else
  echo You MUST run the runPod script first!
fi
